import { FaGuitar, FaTrash } from 'react-icons/fa';
import { FcGoogle } from 'react-icons/fc';
import {
  MdPiano,
  MdOutlineQueueMusic,
  MdOutlineShoppingBag,
  MdMenuBook,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdOutlineUploadFile,
  MdLogout,
  MdOutlineLock,
  MdMailOutline,
  MdOutlineSettings,
  MdOutlineCheck,
  MdUpload,
  MdInfoOutline,
  MdOutlineRemoveCircle,
  MdOutlineFileDownload,
  MdOutlineArrowDropDown,
} from 'react-icons/md';
import { BiUserCircle, BiCoin, BiPencil, BiSearch } from 'react-icons/bi';
import {
  BsFillBarChartFill,
  BsMusicNoteBeamed,
  BsArrowLeft,
  BsDot,
} from 'react-icons/bs';
import { SlArrowLeft, SlArrowRight } from 'react-icons/sl';
import { CgUserList } from 'react-icons/cg';

export {
  FcGoogle,
  FaGuitar,
  FaTrash,
  MdPiano,
  MdOutlineQueueMusic,
  MdOutlineShoppingBag,
  MdMenuBook,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdOutlineUploadFile,
  MdLogout,
  MdOutlineLock,
  MdMailOutline,
  MdOutlineSettings,
  MdOutlineCheck,
  MdUpload,
  MdInfoOutline,
  MdOutlineRemoveCircle,
  MdOutlineFileDownload,
  MdOutlineArrowDropDown,
  BiUserCircle,
  BiCoin,
  BiPencil,
  BsFillBarChartFill,
  BsMusicNoteBeamed,
  BsArrowLeft,
  BsDot,
  BiSearch,
  SlArrowLeft,
  SlArrowRight,
  CgUserList,
};
